#=================================================
# Description: Build ubports using GitHub Actions
# Lisence: MIT
# Contributor: 0312birdzhang
# Maintainer: HandsomeYingyan
# Credit: https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: Build System Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      VENDOR: xiaomi
      DEVICE: cereus
      ANDROID_ROOT: /home/runner/work/halium/

    steps:        
    - name: Checkout
      uses: actions/checkout@master

    - name: Cleanup Disk
      uses: HandsomeYingyan/cleanup-disk-action@v3.0

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git python3 python3-dev \
        python-is-python3 android-tools-adb android-tools-fastboot android-tools-mkbootimg
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "UBports Xiaomi Pad 4 CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"
        mkdir -p $ANDROID_ROOT
        
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
         root-reserve-mb: 1024
         swap-size-mb: 512
         build-mount-path: '$ANDROID_ROOT'

    - name: Downloading source code
      run: |
        source halium.env 
        cd $ANDROID_ROOT 
        ~/bin/repo init -u https://github.com/Halium/android -b halium-9.0 --depth=1 
        repo sync -c -j 16
        #mkdir -p $ANDROID_ROOT/.repo/local_manifests 
        wget https://raw.githubusercontent.com/ubports-xiaomi-cereus/manifest/master/xiaomi_cereus.xml -O $ANDROID_ROOT/halium/devices/manifests/$VENDOR_$DEVICE.xml 
        ./halium/devices/setup cereus
#        ~/bin/repo sync -j8 -c --no-clone-bundle --no-tags
      shell: bash
    
    - name: Build HAL
      run: |
        sudo apt-get install -y python2
        sudo apt remove python-is-python3 python3 python3-dev
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
        sudo apt-get install git-core gnupg flex bison gperf curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip
        chmod +x build-hal.sh
        bash -x build-hal.sh
      shell: bash

#    - name : Upload hybris-boot image
#      uses: actions/upload-artifact@master
#      with:
#        name: hybris-boot image
#        path: /home/runner/work/halium/out/target/product/cereus/hybris-boot.img

#    - name : Upload system image
#      uses: actions/upload-artifact@master
#      with:
#         name: System image
#         path: /home/runner/work/halium/out/target/product/cereus/system.img


    - name : Upload halium-boot image
      uses: actions/upload-artifact@master
      with:
         name: halium-boot image
         path: /home/runner/work/halium/out/target/product/cereus/halium-boot.img
         
    #- name: Start SSH via Ngrok
      #if: ${{ failure() }}
      #uses: dvkunion/CollieTrickster@main
      #with:
         # token: 2c9dcc3512d0f3cdde634436a6cba024
